package pl.edu.uwm.po.lab1;

public class zad7 {
    public static void main(String[] args){
        System.out.println("*******                  * *           * * * *           * * * *        * * * * * * *     *                        * *             *               *            *     *               *          * *          * *         *        * * *          *           *     *         * * * * * *     * * * * *        ");
        System.out.println("*       *               *   *          *       *       *         *      *                 *                       *   *            *               *            *     *               *         *   *         *  *        *      *       *        *           *     *        *                       *         ");
        System.out.println("*     *                *     *         *        *     *           *     *                 *                      *     *           *               *            *     *               *        *     *        *   *       *     *         *       *           *     *       *                       *          ");
        System.out.println("********              *       *        *         *   *             *    *                 *                     *       *          *               *            *     *               *       *       *       *    *      *    *           *      *           *     *      *                       *           ");
        System.out.println("*      *             * * * * * *       *         *   *             *    * * * * * * *     *                    * * * * * *         *       *       *            *     *       *       *      * * * * * *      *     *     *    *           *      *     *     *     *     *                       *            ");
        System.out.println("*       *           *           *      *         *   *             *                *     *                   *           *        *     *   *     *            *     *     *   *     *     *           *     *      *    *     *         *       *    * *    *     *     *                      *             ");
        System.out.println("*        *         *             *     *        *     *           *                 *     *                  *             *       *   *       *   *            *     *   *       *   *    *             *    *       *   *      *       *        *   *   *   *     *     *                     *              ");
        System.out.println("*         *       *               *    *       *       *         *                  *     *                 *               *      * *           * *            *     * *           * *   *               *   *        *  *       *     *         *  *     *  *     *      *                   *               ");
        System.out.println("*          *     *                 *   * * * *          * * * * *       * * * * * * *     * * * * * * *    *                 *     *               *            *     *               *  *                 *  *         * *        * * *          * *       * *     *       * * * * * * *     * * * * * * *    ");
    }
}
